### ISSUE TITLE
Defining best practice for `__version__`.

### ISSUE THREAD

**Issue by SylvainCorlay** [pybind/python_example#12]
@wjakob @dean0x7d @jmabille
In projects using pybind11 that are pure C++, you end up with having to specify the package version number both
 - in `setup.py` to specify the version number for the python module.
 - in a module-level `__version__` attribute, provided by the c++ code.

In order to not have to change the version number in two locations at each release, the `__version__` module attribute is computed based on a macro set in a `_version.hpp` header. 

The setup.py overrides that file to set the `__version__` string to the one specified in `setup.py`.

```python
with open('./include/_version.hpp', 'w') as f:
    f.write('''
#ifndef PYTHON_EXAMPLE_VERSION_HP
#define PYTHON_EXAMPLE_VERSION_HPP
    #define PYTHON_EXAMPLE_VERSION "%s"
#endif
''' % __version__)
```

and `_version.hpp` is in the `.gitignore`so that these changes don't get checked in.

Do you think of a better way to do this? Should we include this method in the example projects?

**Comment by dean0x7d** [comment]
If I understood the intention correctly - to make `setup.py` be the only place where a version should be specified manually - I think it would be cleaner to pass `PYTHON_EXAMPLE_VERSION` as a compiler `-D` flag, rather than create a new header file.

**Comment by wjakob** [comment]
Not sure I follow -- how would the C++ code use this variable PYTHON_EXAMPLE_VERSION, i.e. why would it need to know its version?

**Comment by SylvainCorlay** [comment]
So that the exposed python module to expose a `__version__` attribute. Except that the module is written in pure C++.

**Comment by wjakob** [comment]
Aha, I see. Specifying -DPYTHON_EXAMPLE_VERSION=.. as a compiler flag would indeed seem easier then.

**Comment by SylvainCorlay** [comment]
Except that -D command line option will also have to be specified for people who use an IDE or another environment for development.

**Comment by wjakob** [comment]
The question then is whether ``setup.py`` is the canonical way to build the plugin? If somebody uses an IDE and PYTHON_EXAMPLE_VERSION is not defined, I suppose the easiest way is simply to not set ``__version__``.

**Comment by SylvainCorlay** [comment]
> The question then is whether setup.py is the canonical way to build the plugin?

Definitly IMO.

**Comment by dean0x7d** [comment]
So if `setup.py` is the only place invoking the build, does it matter if an IDE or any other editor environment isn't aware of the macro?
It could easily guarded:
```c++
#ifdef PYTHON_EXAMPLE_VERSION
m.attr("__version__") = PYTHON_EXAMPLE_VERSION;
#endif
```
I don't think the situation would be any different with the header.

**Comment by SylvainCorlay** [comment]
Good point. (we should have a fallback value for __version__ though).

**Comment by dean0x7d** [comment]
Maybe this is something that the library should handle automatically, if `__version__` should truly be an intrinsic part of every extension module.

What do you think of this proposal: The `PYBIND11_PLUGIN` macro automatically sets `__version__` to the value of `PYBIND11_PLUGIN_VERSION` if it's defined by the user. Otherwise it defaults to "1.0.0". Since the `PYBIND11_PLUGIN` macro is doing all this internally, there would be no code needed on the user side.

This also makes `PYBIND11_PLUGIN_VERSION` the canonical place to set the pybind11 module version. It would not need to have a project-specific name. In `setup.py` the compiler flag would be set to `"-DPYBIND11_PLUGIN_VERSION" = + self.distribution.get_version()` where `self` is the `build_ext` instance.

**Comment by SylvainCorlay** [comment]
Why not, although it might be a bit overkill. I am fine with having some boilerplate.

**Comment by dean0x7d** [comment]
I really hate boilerplate. But I do see the overkill here and I don't want to push this proposal if it's disliked. If there is any interest, I am willing to prepare a PR.

**Comment by SylvainCorlay** [comment]
Well, the whole point of projects like python_example / cmake_example is to identify boilerplate. When it is more stable, we could migrate to a cookiecutter template.
