### ISSUE TITLE
add pybind-module as a submodule

### ISSUE THREAD

**Issue by benmaier** [pybind/python_example#26]
I'm sorry if this is a trivial question. I'm currently writing a package where only some functions are written in C++. It seems a bit redundant to me to split this in two packages. Is there a possibility to compile the C++-part as a submodule of the whole package whereas other submodules would be pure python?

**Comment by SylvainCorlay** [comment]
It is certainly possible, but I would generally not recommend this as people would end up writing different extension modules with different version of the pybind11 headers. If ever these need to link with each other, you will end up with binary incompatibilities.

This is generally bad practice to vendor third-party libraries if you have a package manager.

**Comment by benmaier** [comment]
I don't know if I understood your reply correctly, if I only have one package with a mixture of C++ and Python, where is the point where any incompatibilities would occur?

Nevertheless, my question was apparently answered in an [issue of the original package](https://github.com/pybind/pybind11/issues/1004), so I'm going to close this one. Thanks for your help!

**Comment by SylvainCorlay** [comment]
> I don't know if I understood your reply correctly, if I only have one package with a mixture of C++ and Python, where is the point where any incompatibilities would occur?

The situation occurs when multiple python extensions *link* to each other, not when you make a standalone extension only to be called from Python.

Also, from a packaging perspective, if you want your work to be packaged for e.g. a Linux distribution, it is generally against policy to vendor code that is in fact in other packages.

**Comment by benmaier** [comment]
maybe I got something completely wrong, but my original question was concerning how to structure a Python package where one submodule `A` is written in C++ and compiled using pybind11 whereas another submodule `B` is pure Python. This shouldn't be so different from situations where I have two submodules which are both in pure Python. Is that bad practice?

I'm sorry if I worded that in a strange manner

**Comment by t-vi** [comment]
Hi,
is there a way to actually put my C++-Code inside the module hierachy?
With regular Extensions, I can specify `mymodule._C` or so as the extension name and have `mymodule.__init__.py` as the interface to the world.
This seems to not work with pybind if I try. Do you have a hint whether I am missing something?
Thank you

Thomas

**Comment by t-vi** [comment]
Indeed. Thank you! (So it was the PyTorch template that tricked me into thinking it didn't work, but that is an issue elsewhere.)
