### ISSUE TITLE
get_include seems to be broken with pip version 10.0.

### ISSUE THREAD

**Issue by rmjarvis** [pybind/python_example#30]
pip version 10.0 doesn't have a `pip.locations`.  So `pybind11.get_include()` just returns `'include'` after the ImportError.

Workaround for now is to require pip version 9.0.3.  But ideal if you could figure out what the right pip function to call is when `pip.__version__ > '10.0'`.

**Comment by SylvainCorlay** [comment]
Thanks for the report!

Cress referencing https://github.com/pybind/pybind11/pull/1190

**Comment by rmjarvis** [comment]
Ah.  Thanks for the cross-reference.  I had meant to be reporting this in the pybind11 issues, but I guess I missed.  Closing this in preference for that issue that seems to already have a fix in place.
