### ISSUE TITLE
Fixes for MinGW

### ISSUE THREAD

**Issue by inducer** [pybind/python_example#35]
These changes help PyOpenCL build with pybind11 on MinGW:

https://gitlab.tiker.net/inducer/pyopencl/merge_requests/52/diffs

It would likely be useful to incorporate them here as well.

cc @isuruf

**Comment by SylvainCorlay** [comment]
PR welcome!

**Comment by isuruf** [comment]
https://github.com/pybind/python_example/pull/36

**Comment by isuruf** [comment]
Fixed now
