### ISSUE TITLE
Difficulty uploading to pypi?

### ISSUE THREAD

**Issue by franklynwang** [pybind/python_example#84]
Hi all, 

Thanks for a great package! I'm trying to upload my package (https://github.com/franklynwang/quick-sketches) to PyPi. My Github Actions (https://github.com/franklynwang/quick-sketches/runs/3083040093) work for everything except the upload, but the upload to pypi action says that I have an issue with my token, which I have triple-checked and it doesn't appear to be the case. 

My wheels.yml file is here: https://github.com/franklynwang/quick-sketches/blob/master/.github/workflows/wheels.yml. 

Please let me know what other information I can provide to be helpful.

**Comment by henryiii** [comment]
Did this get solved? It got missed, sorry.

**Comment by franklynwang** [comment]
Hi, it did get solved! The fix was adding `verbose: true` in the github action: https://github.com/franklynwang/quick-sketches/commit/a725495afcc541c6a98b9c59a38a90157b6710ed.
