### ISSUE TITLE
Why the same code can be built and installed on Linux and macOS but not on Windows?

### ISSUE THREAD

**Issue by sun1638650145** [pybind/python_example#96]
I can use `python setup.py install` to install on Linux or macOS, but it will report an error on Windows. And this kind of error will only happen if you add a directory structure to the cpp source code, like the following `pybind_example/backend/ops.cc` (if it is such a structure `pybind_example/ops.cc`, you can successful compilation).
<img width="682" alt="截屏2021-12-13 下午7 22 42" src="https://user-images.githubusercontent.com/47380395/145806549-5c14dad2-b84d-474f-855e-90879a47af01.png">
The following is the error message:

```powershell
LINK : error LNK2001: unresolved external symbol PyInit_pybind_example/backend/ops
build\temp.win-amd64-3.7\Release\pybind_example/backend\ops.cp37-win_amd64.lib : fatal error LNK1120: 1 unresolved externals
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\link.exe' failed with exit status 1120
```

I have been confused for three days, and the same error appears when using `skbuild`. I am a newbie in windows development.

**Comment by henryiii** [comment]
Should the paths be converted to Windows style? Those should get turned into "\" somewhere, I'd think. Windows should see `pybind_example\backend\ops` as a path. Just a thought.

**Comment by sun1638650145** [comment]
@henryiii I tried the ideas you provided to solve the problem. So writing a function separately to modify the path format according to different OS is also a solution.
